apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - DaleWYZ/deployjx-1219
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - DaleWYZ/go-http-1222
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - DaleWYZ/go-http-jx-1226
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - DaleWYZ/go-http-new-1226
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - DaleWYZ/golang-1219
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - DaleWYZ/golangtest11
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - DaleWYZ/jx-deploy-test-1221
      require_self_approval: true
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps:
        env/prow/job.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
    external_plugins:
      DaleWYZ/deployjx-1219:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      DaleWYZ/go-http-1222:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      DaleWYZ/go-http-jx-1226:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      DaleWYZ/go-http-new-1226:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      DaleWYZ/golang-1219:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      DaleWYZ/golangtest11:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      DaleWYZ/jx-deploy-test-1221:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
    label:
      additional_labels: null
    owners: {}
    plugins:
      DaleWYZ/deployjx-1219:
      - config-updater
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      DaleWYZ/go-http-1222:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      DaleWYZ/go-http-jx-1226:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      DaleWYZ/go-http-new-1226:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      DaleWYZ/golang-1219:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      DaleWYZ/golangtest11:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      DaleWYZ/jx-deploy-test-1221:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    triggers:
    - repos:
      - DaleWYZ/deployjx-1219
      trusted_org: DaleWYZ
    - repos:
      - DaleWYZ/go-http-1222
      trusted_org: DaleWYZ
    - repos:
      - DaleWYZ/go-http-jx-1226
      trusted_org: DaleWYZ
    - repos:
      - DaleWYZ/go-http-new-1226
      trusted_org: DaleWYZ
    - repos:
      - DaleWYZ/golang-1219
      trusted_org: DaleWYZ
    - repos:
      - DaleWYZ/golangtest11
      trusted_org: DaleWYZ
    - repos:
      - DaleWYZ/jx-deploy-test-1221
      trusted_org: DaleWYZ
    welcome:
    - message_template: Welcome
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
