apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: DaleWYZ
    provider: github
    repository: jx-deploy-test-1221
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: dalewyz-jx-deploy-test-1221
  namespace: jx
spec:
  httpCloneURL: https://github.com/DaleWYZ/jx-deploy-test-1221.git
  org: DaleWYZ
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: jx-deploy-test-1221
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/DaleWYZ/jx-deploy-test-1221
